[features]
seeds = false
[programs.localnet]
anchor_auction = "4gBimFyVziw8LLDDADg4atmv2np4836deDJmAvU6aVJB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/zunairajaved/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
