[features]
seeds = false
[programs.localnet]
anchor_auction = "EXvQ4Q2MaXvyPXQpaWcYZzeiWdoNEGPQD84jRkj9j4W6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/zunairajaved/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
